package com.example.sketchtrain.other

object IntentExtras {
    //TRAINING
    const val TRAINING_ID = "TRAINING_ID"
    const val TRAINING_DESCRIPTION = "TRAIN_DESCRIPTION"
    const val TRAINING_TYPE = "TRAINING_TYPE"
    const val  TRAINING_DATE = "TRAINING_DATE"
    const val ROUTINE_LIST = "ROUTINE_LIST"

    //ROUTINE
    const val ROUTINE_ID = "ROUTINE_ID"
    const val ROUTINE_DESCRIPTION = "ROUTINE_DESCRIPTION"
    const val EXERCISE_LIST = "EXERCISE_LIST"

    //EXERCISE
    const val EXERCISE_ID = "EXERCISE_ID"
    const val EXERCISE_NAME = "EXERCISE_NAME"
    const val EXERCISE_MW1R = "EXERCISE_MW1R"
    const val EXERCISE_IS_POWER = "EXERCISE_IS_POWER"
    const val EXERCISE_IS_ACCESORY = "EXERCISE_IS_ACCESORY"
    const val SET_LIST = "SET_LIST"
    const val EXERCISE_MAXWEIGHT = "EXERCISE_MAXWEIGHT"
    const val EXERCISE_MAXREPS = "EXERCISE_MAXREPS"

    //SET
    const val SET_NUMBER = "SET_NUMBER"
    const val SET_WEIGHT = "SET_WEIGHT"
    const val SET_REPS = "SET_REPS"

    //PROGRESS
    const val PROGRESS_ID = "PROGRESS_ID"
    const val PROGRESS_EXERCISE_NAME = "PROGRESS_EXERCISE_NAME"
    const val PROGRESS_WEIGHT = "PROGRESS_WEIGHT"
    const val PROGRESS_REPS = "PROGRESS_REPS"
    const val PROGRESS_DATE = "PROGRESS_DATE"
    const val PROGRESS_ID_EXERCISE = "PROGRESS_ID_EXERCISE"

    //OTHER
    const val EDITING_POSITION = "EDITING_POSITION"
    const val REPLACE_POSITION = "REPLACE_POSITION"
    const val DO = "DO"

}
